### ISSUE TITLE
Som en AccountProvider vill jag kunna ta bort en användare

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_AccountProvider#12]
## Tasks
- [ ] Sök efter användaren efter id i databasen
- [ ] skapa metoden DeleteUserAsync
  - Metoden ska radera användaren ur databasen
  - Kontrollera att användaren har blivit borttagen ur databasen
- [ ] Returnera rätt statuskod ifall det lyckats eller misslyckats

## Acceptanskriterier
Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven: 
 
1. Det ska gå att ta bort en användare baserat på id
2. Användaren ska raders ur databasen
3. Rätt statuskod skickas till klienten

  

 ## Testfallsbeskrivningar
Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls. 

Testfall 1: Användaren lyckas tas bort
   
Förutsättningar: Klienten vill ta bort en användare

Steg: 
1. Sök i databasen efter en användare med samma id som ska tas bort
2. Radera användaren ur databasen

Förväntat resultat: En användare har tagits bort och vi har fått en status kod 200 tillbaka.

Testfall 2: Användaren lyckas inte tas bort 
   
Förutsättningar: Klienten vill ta bort en användare

Steg: 
1. Sök i databasen efter en användare med samma id som ska tas bort
2. Försök radera användaren ur databasen

Förväntat resultat: Användaren lyckades inte tas bort och vi får tillbaka en statuskod 404.

Testfall 3: Användarens Id hittas inte i databasen 
   
Förutsättningar: Klienten vill ta bort en användare

Steg: 
1. Försöker söka efter användarens id i databasen

Förväntat resultat: Användarens id hittade inte och lyckades inte tas bort och vi får tillbaka en statuskod 404.

![Image](https://github.com/user-attachments/assets/aa4352ae-6a97-4652-ac01-250ea99fa18c)
