### ISSUE TITLE
Som en AccountProvider vill jag kunna ta bort en address från en användare

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_AccountProvider#13]
## Tasks
- [ ] Sök efter användarens id i databasen och hämta sen ut AddressEntity
- [ ] Skapa metoden DeleteAddressAsync
  - Metoden ska radera användarens adress ur databasen
  - Kontrollera att adressen har blivit borttagen ur databasen
- [ ] Returnera rätt statuskod ifall det lyckats eller misslyckats

## Acceptanskriterier
Dessa beskriver när user storyn anses vara klar och uppfyller affärskraven: 
 
1. Det ska gå att ta bort en användares adress baserat på användarens id
2. Adressen ska raderas ur databasen
3. Rätt statuskod skickas till klienten

 ## Testfallsbeskrivningar
Dessa beskriver testfall för att säkerställa att acceptanskriterierna uppfylls. 

Testfall 1: Adressen lyckas tas bort
   
Förutsättningar: Användaren vill ta bort sin adress

Steg: 
1. Sök i databasen efter en användare med samma id som ska tas bort
2. Sök efter adress entiteten kopplad till användaren
3. Radera adressen ur databasen

Förväntat resultat: En användares adress har tagits bort och vi har fått en status kod 200 tillbaka.

Testfall 2: Adressen lyckas inte tas bort 
   
Förutsättningar: Användaren vill ta bort sin adress

Steg: 
1. Sök i databasen efter en användare med samma id som ska tas bort
2. Sök efter adress entiteten kopplad till användaren
2. Försök radera adressen ur databasen

Förväntat resultat: Användarens adress lyckades inte tas bort och vi får tillbaka en statuskod 500.

Testfall 3: Det går inte att hitta en adress entitet kopplad till användarens id
   
Förutsättningar: Användaren vill ta bort sin adress

Steg: 
1. Försöker söka efter adress baserat på användarens id i databasen

Förväntat resultat: Adress entitet kopplas till användarens id hittades inte och lyckades inte tas bort och vi får tillbaka en statuskod 404.

![Image](https://github.com/user-attachments/assets/ad19f9a1-419a-4ed5-89d3-6b335c782ad3)
